FROM frolvlad/alpine-glibc:alpine-3.12
MAINTAINER Marthen Luther <marthen.luther@oracle.com>
ENV MYSQL_HOST=mysql \
    DO_NOT_INITIALIZE=never \
    ORACLE_HOST=oracle \
    VERSION=v0.12
RUN apk -U upgrade \
        && apk add libstdc++
COPY target/petclinic-jpa .
EXPOSE 8080
ENTRYPOINT ["/petclinic-jpa"]